### ISSUE TITLE
[FEAT] Show correct font in Font Family selector

### ISSUE THREAD

**Issue by yjeroen** [arcanistzed/custom-fonts#10]
![image](https://user-images.githubusercontent.com/1303988/150646825-38a5698c-7d29-4f51-946a-a97357ce9e1c.png)

Would be great if the Font Family option selector showed the text in their actual respective fonts.

Furthermore, would be great to have these two fields as selector inputs:

![image](https://user-images.githubusercontent.com/1303988/150646857-7fb70606-5a8e-4500-b5a9-252c3971841d.png)

**Comment by arcanistzed** [comment]
> Furthermore, would be great to have these two fields as selector inputs

Could you create a separate issue for this?
Thank you
