### ISSUE TITLE
[BUG] Error detected in module. It is likely this module has not been updated for FVTT Version 9.

### ISSUE THREAD

**Issue by jensenator** [arcanistzed/custom-fonts#11]
When starting Foundry on a server, I get this error message:
![Screenshot 2022-01-27 103904](https://user-images.githubusercontent.com/74561762/151333960-ded039c0-75ac-44d8-953e-f7b9965adcbe.png)

**Comment by arcanistzed** [comment]
What does it say in the console?

**Comment by arcanistzed** [comment]
This is most likely a conflict with another module. Try using [Find the Culprit](https://foundryvtt.com/packages/find-the-culprit/) to identify which module is causing this.

**Comment by jensenator** [comment]
![Screenshot 2022-01-28 083145](https://user-images.githubusercontent.com/74561762/151506045-1bc2f63f-7598-4e5c-8011-cba6018852fe.png)

I uploaded this on Discord too.

**Comment by arcanistzed** [comment]
b9f2f885b8c0eee79570c6437d30db4d3a9fdccf
