### ISSUE TITLE
[Bug]: Errors in console when changing settings

### ISSUE THREAD

**Issue by Jonwh25** [arcanistzed/custom-fonts#12]
### Expected Behavior

I shouldn't see errors in the console log when changing a setting.

### Current Behavior

I change a setting and it throws an error in the log.

![image](https://user-images.githubusercontent.com/60674327/164801590-274d0ead-19da-4af8-afd7-27dffa533c8e.png)

### Steps to Reproduce

1. Pick a setting 
2. Change a setting

### Version

0.5.3

### Foundry VTT Version

9.269

### Operating System

Linux (Ubuntu 20.04)

### Browser / App

Chrome

### Game System

dnd5e 1.5.7

### Modules Disabled

- [X] I can confirm that disabling all of my other modules doesn't fix this issue.

**Comment by arcanistzed** [comment]
What is `HelpersSettingsConfig` in that screenshot? Are you sure that all modules are disabled?

**Comment by arcanistzed** [comment]
I'll tentatively close this issue until you confirm

**Comment by Jonwh25** [comment]
Keep it closed. I'm not seeing it now.
