### ISSUE TITLE
[Bug]: Option "Sharper Text Drawings" crash custom fonts module

### ISSUE THREAD

**Issue by Danii0206** [arcanistzed/custom-fonts#18]
### Expected Behavior

Enabling the option "Sharper Text Drawings" gives sharper text drawings.

### Current Behavior

Enabling the option crashes custom-fonts. All drawings with custom fonts display the standard foundry font. Theres an error message in the console:
```
foundry.js:58524 Custom Fonts: Error detected in module. (See JS Console)
fetch @ foundry.js:58524
```

### Steps to Reproduce

Enable the option "Sharper text drawings".
Save settings. (Foundry reloads.)

### Version

0.7.2

### Foundry VTT Version

10.285

### Operating System

Linux

### Browser / App

Native Electron App

### Game System

dsa5 (4.1.0)

### Modules Disabled

- [X] I can confirm that disabling all of my other modules doesn't fix this issue.

**Comment by arcanistzed** [comment]
See #21
