### ISSUE TITLE
[Bug]: Warnings, and potential Foundry crash

### ISSUE THREAD

**Issue by Crowguard** [arcanistzed/custom-fonts#19]
### Expected Behavior

Drawings on a scene shouldn't be resulting in errors for each drawing.

### Current Behavior

![image](https://user-images.githubusercontent.com/99844555/193880408-e3c1ae21-08d9-4a5c-b01e-58956675dd03.png)

On a scene with drawings, with Custom Fonts active, I receive this warning for every single drawing on the scene.

(This part is just a problem my scene, but the errors can build up enough to crash my tab)

### Steps to Reproduce

1. Make scene
2. Place lots of drawings
3. Switch scenes then back
4. Check the console.

### Context

![image](https://user-images.githubusercontent.com/99844555/193881041-0105be80-5f2e-4222-a85c-acaf3f005cab.png)
![image](https://user-images.githubusercontent.com/99844555/193881350-fd8a5d99-bdbd-4f51-b09b-03d893f02e46.png)

### Version

0.7.2

### Foundry VTT Version

10.286

### Operating System

Windows

### Browser / App

Firefox

### Game System

D&D 5e 2.03

### Modules Disabled

- [X] I can confirm that disabling all of my other modules doesn't fix this issue.

**Comment by arcanistzed** [comment]
How does this cause a crash? I understand that it will slow things down if you have DevTools open, but otherwise these warnings should be completely harmless. If you'd like to silence them, you can install the DevMode module which has an option for that. Also, make sure that you have disabled the Sharper Text Drawings feature if you're on v10, since it no longer works.

**Comment by Crowguard** [comment]
Apologies; I assumed my Foundry crashing was related to the errors; both started after I turned Custom Fonts back on. I'm noticing my Foundry is still having issues with freezing/crashing without CF on now, so I'll have to keep experimenting.
