### ISSUE TITLE
[Bug]: Error: CONFIG.fontFamilies is deprecated. Please use CONFIG.fontDefinitions instead.

### ISSUE THREAD

**Issue by yjeroen** [arcanistzed/custom-fonts#20]
### Expected Behavior

No warning errors

### Current Behavior

![image](https://user-images.githubusercontent.com/1303988/200179831-d3f75221-197b-475c-bddb-b639675d9b76.png)

![image](https://user-images.githubusercontent.com/1303988/200179930-ec927ce4-26e4-4aa1-b290-0907396b6a0a.png)

### Steps to Reproduce

1. Enable module

### Version

0.7.2

### Foundry VTT Version

10.288

### Operating System

Windowsd

### Browser / App

Chrome

### Game System

Forbidden Lands 10.0.0

### Modules Disabled

- [X] I can confirm that disabling all of my other modules doesn't fix this issue.

**Comment by arcanistzed** [comment]
Removing these warnings requires foregoing v9 compatibility

**Comment by yjeroen** [comment]
@arcanistzed, wouldn't it be possible to detect if the user is using v9 and only then use CONFIG.fontFamilies instead of CONFIG.fontDefinitions?

Because the deprecated warning means that in the future it will be fully removed in a future FoundryVTT update?

**Comment by arcanistzed** [comment]
Yes, it is possible to do that, but it adds complexity to the code. I prefer to leave it as-is until I'm ready to drop v9 support once v11 or v12 is out.
