### ISSUE TITLE
[Bug]: LibWrapperPackageError: Error detected in module Custom Fonts.

### ISSUE THREAD

**Issue by yjeroen** [arcanistzed/custom-fonts#23]
### Expected Behavior

No console error

### Current Behavior

![image](https://user-images.githubusercontent.com/1303988/201146618-37393cef-3e5f-44cf-9058-bdb490789ebc.png)

### Steps to Reproduce

1. Enable LibWrapper Module
2. Enable custom-fonts Module
3. Enable Sharper Text Drawings

### Version

0.7.2

### Foundry VTT Version

V10 build 288

### Operating System

Windows

### Browser / App

Native Electron App, Chrome

### Game System

Symbaroum

### Modules Disabled

- [X] I can confirm that disabling all of my other modules doesn't fix this issue.

**Comment by arcanistzed** [comment]
See #21
