### ISSUE TITLE
[Bug]: Console Error on Foundry v10

### ISSUE THREAD

**Issue by jdgcoop** [arcanistzed/custom-fonts#24]
### Expected Behavior

Custom Fonts used to launch without error

### Current Behavior

With each launch of Foundry vtt v10, Custom Fonts displays this error: Custom Fonts: Error detected in module. (See JS Console)

Appears to be an issue with a Libwrapper call.  I tested again with only the following modules enabled.

1. Custom Fonts
2.  Librwapper
3. Tidy UI

And received the same errors as shown below.

### Steps to Reproduce

Happens everytime I launch Foundry vtt v10 with my set of modules.  Here is what I have running:
Active Modules:
----------
Alpha Suit v;
Art Gallery v;
Break Time v;
Chat Images v;
Compendium Folders v;
Custom Fonts v;
Custom Nameplates v;
Data Toolbox for FoundryVTT v;
DF Chat Enhancements v;
Dice So Nice! v;
Dice Tray v;
dlopen v;
Dynamic effects using Active Effects v;
Ernie's Modern UI v;
Find the culprit v;
Foundry Community Macros v;
Foundry Community Tables v;
FXMaster v;
JTCS - Art Gallery v;
Lancer Initiative v;
lib - Color Settings v;
Library: Chat Commands v;
libWrapper v.0;
Module Compatibility Checker v;
Monk's Active Tile Triggers v;
Monk's Enhanced Journal v;
Monk's Little Details v;
Monk's Scene Navigation v;
Monk's TokenBar v;
Monk's Wall Enhancement v;
PopOut! v;
QuickScale v;
Scene Transitions v;
Settings Extender v;
Simple Calendar v;
Simplefog - Manual Fog of War v;
socketlib v;
SoundBoard by Blitz v;
SoundBoard Pack - Blitz Free Pack v;
SoundBoard Pack - Community v;
SoundFx Library v;
The Forge v;
The Forge: Compendium Library v;
The Forge: More Awesomeness v;
Tidy UI - Game Settings v;
Times Up v;
Token Attacher v;
Tokenizer v;
Token Magic FX v;
VuePort: Let the Light in! v;
X-Card v;

Inactive Modules:
----------
Ace Library v;
Better Roofs v;
Combat Utility Belt v;
Easy Exports v;
Enhanced Terrain Layer v;
Export Sheet to PDF v;
GM Screen v;
Hide GM Rolls v;
Keybind Lib v;
Levels v;
libCaptions v;
Library: DF Hotkeys v;
Library: DF Module Buttons v;
Library: Scene Packer v;
LiveKit AVClient v;
Math.js vvtt2;
Michael Ghelfi Studios Audio Pack v;
Ownership Viewer v;
Polished UI v;
Show Notes v;
SortableJS vfvtt1;
Token Variant Art v;
Torch v;
Universal Battlemap Importer v;
Wall Height v;

### Context

Here is the console information

LibWrapperPackageError: Error detected in module Custom Fonts.

This is *not* a libWrapper bug.
Find information about this module here: https://github.com/arcanistzed/custom-fonts
Report this issue here: https://github.com/arcanistzed/custom-fonts/issues/new/choose

== Technical Details:
Detected by libWrapper.
Package ID= custom-fonts
Error= Can't wrap 'Drawing.prototype._createText', target does not exist or could not be found.

[Detected 1 package: custom-fonts]
    at new 🎁constructor (libWrapper-wrapper.js:111:11)
    at libWrapper-api.js:82:18
    at se (libWrapper-api.js:155:9)
    at 🎁register [as register] (libWrapper-api.js:525:14)
    at CustomFonts.sharperTextDrawings (custom-fonts.js:386:14)
    at new CustomFonts (custom-fonts.js:38:70)
    at Object.fn (custom-fonts.js:415:24)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at Game.initialize (foundry.js:7767:11)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁libWrapperInit (libWrapper-api.js:805:11)
onError @ foundry.js:747
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁Hooks.onError#lib-wrapper @ listeners.js:137
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
#call @ foundry.js:728
callAll @ foundry.js:681
initialize @ foundry.js:7767
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁libWrapperInit @ libWrapper-api.js:805
await in 🎁libWrapperInit (async)
🎁Game.prototype.initialize#0 @ libWrapper-wrapper.js:187
window.addEventListener.once @ foundry.js:79319
foundry.js:58907 Custom Fonts: Error detected in module. (See JS Console)

### Version

0.72

### Foundry VTT Version

10.290

### Operating System

Win 11

### Browser / App

Chrome

### Game System

Cortex Prime or DnD 5e

### Modules Disabled

- [ ] I can confirm that disabling all of my other modules doesn't fix this issue.

**Comment by arcanistzed** [comment]
See #21
