### ISSUE TITLE
[Bug]: Unable to fetch Google Fonts: blocked by CORS policy

### ISSUE THREAD

**Issue by CatbotTsumi** [arcanistzed/custom-fonts#25]
### Expected Behavior

Expecting the module to grab the fonts from google fonts and make them available.

### Current Behavior

When saving a comma separated list of google font names, an error shows up and fonts are not loaded.

![Error logs image](https://i.imgur.com/ML8rekp.png)

### Steps to Reproduce

1. Configure Game Settings
2. Custom Fonts
3. Fill in any font name(s) in the **Google Fonts** text box
4. Save Changes
5. Error!

### Version

0.7.2

### Foundry VTT Version

V10 Build 290

### Operating System

Windows 10 N

### Browser / App

Chrome

### Game System

dnd5e (2.0.3)

### Modules Disabled

- [X] I can confirm that disabling all of my other modules doesn't fix this issue.

**Comment by arcanistzed** [comment]
Are you certain that you're using the exact name of the font with no differences in spacing or punctuation?

**Comment by CatbotTsumi** [comment]
The problem seemed to resolve after fixing capitalizations
