### ISSUE TITLE
[BUG] default font directory not found

### ISSUE THREAD

**Issue by Danii0206** [arcanistzed/custom-fonts#7]
Hi,

since the last update (0.1.0 -> 0.2.1) I get an error notification (on canvas, not in console) saying 

`custom fonts | The configuration for the font directory is currently invalid and fonts could not be loaded: Directory fonts does not exist or is not accessible in this storage location`

I did not change the default setting. It is still "fonts" and the directory picker shows the correct directory.

I am on linux which may be a contributing factor. I'll attach the foundry system report below.

Kind regards
Danii

PS: Please use the console for error messages, too, because we can copy paste from there. Getting the message above included about 10 times reloading Foundry to get it displayed again. The canvas notifications fade out too fast for slow writers like me. ;)

Foundry Virtual Tabletop: Version 9, 9.242
Game System: vtm5e, 1.8.0
Active Modules: 18
Performance Mode: 2

OS: Unknown
Client: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) FoundryVirtualTabletop/9.0.0 Chrome/94.0.4606.81 Electron/15.3.4 Safari/537.36
GPU: ANGLE (AMD, AMD Radeon RX 5700 XT (NAVI10), OpenGL 4.6 (Core Profile) Mesa 21.0.3)
Max Texture Size: 16384

Scene: 2080 x 2655 | Grid Size: 100 | Padding Percentage: 0.25
Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 0

Actors: 6 | Items: 0 | Journal: 20 | Rollable Tables: 0 |
Playlists: 0 | Compendium Packs: 13 | Chat Messages: 0

**Comment by arcanistzed** [comment]
This is because the module is expecting you to create a local font directory at the location you have chosen in your user data: `Data/fonts`.
I could "fix" this by automatically creating that folder, but I wasn't certain about this.

I'll throw it in the console next time too :wink:

**Comment by Danii0206** [comment]
Oh, it points to user data? When I open the directory picker next to the path-textfield it points me to the fonts folder in core data. 

Edit: As probably not everyone is using this feature, I wouldn't want an empty folder created. Maybe just don't give a default value for this option?

**Comment by arcanistzed** [comment]
Yeah. I'm not sure why it points to the core folder. It is indeed only reading the user data.
I agree that no default value is a good idea

**Comment by arcanistzed** [comment]
37b738df9127d2d2dbed7c1ca7c7121bff3aa81a
